package org.mountcloud.demo.user.entity;

import org.mountcloud.springproject.common.entity.BaseEntity;

public class User extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userName
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.roles
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    private String roles;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userName
     *
     * @return the value of t_user.userName
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userName
     *
     * @param username the value for t_user.userName
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.roles
     *
     * @return the value of t_user.roles
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    public String getRoles() {
        return roles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.roles
     *
     * @param roles the value for t_user.roles
     *
     * @mbg.generated Mon Jan 20 11:41:43 CST 2020
     */
    public void setRoles(String roles) {
        this.roles = roles;
    }
}